### PR TITLE
Refactoring toolbar

### PR DESCRIPTION
**Pull request by xhruso00**
Moving out toolbar out of controller + fixing inconsistencies for selection

### CODE REVIEW

**Comment by brunophilipe** [comment]
I like the intention of separating the toolbar code to a different controller, but I don't like the erratic behaviour of removing and inserting items on the toolbar every time it needs to change that you have implemented. This looks completely wacky to the user – for code that should be refactoring behaviour. 

I have never seen any Mac App doing this, at least not visibly. I know the current behaviour of the toolbar is not optimal, and can sometimes become inconsistent with the formula selection. But unless this can be improved, I am not merging this request as of now.

Perhaps there is a way to "freeze" the toolbar while it is being updated?

**Comment by xhruso00** [comment]
I will change it's behaviour to multiple actions in single button as you prefer.

**Comment by xhruso00** [comment]
Changed as requested.The simplest way to freeze it is to remove target or action so autovalidation will grey the button.

**Comment by brunophilipe** [comment]
It looks much better now, however in Yosemite the toolbar items go blank after the toolbar changes. I inspected the views with the UI debugger, and the NSImageView inside the NSToolbarItem is collapsing (width and height equal to zero). I am trying to fix it though.

**Comment by xhruso00** [comment]
Tested just on El Capitan. Simple solution can be to use blank transparent image.

**Comment by brunophilipe** [comment]
Yup, that's the same solution I found. I am also taking the change to include new toolbar icons on OS X 10.10+

**Comment by brunophilipe** [comment]
Merged on commit fa33416d3afec9c619f14d69ff52a0da57fa1dd5

**Pull request merged**
