### PR TITLE
Adding tests for formula parsing

### PR DESCRIPTION
**Pull request by xhruso00**
Added new test set to ensure that parsing is correct. Added class for formula options. Adapted BPFormula to be testable.

### CODE REVIEW

**Comment by brunophilipe** [comment]
Why removing the precompiled header?

**Comment by xhruso00** [comment]
Prefix file hide dependencies. I wasn't able to compile tests without including it. Object like formula shouldn't depend on other files (increases build time & code can't be reused). 
http://qualitycoding.org/precompiled-headers/

**Comment by brunophilipe** [comment]
Hm ok, makes sense.

**Comment by brunophilipe** [comment]
Thanks, these tests were definitely needed. :+1:

**Comment by xhruso00** [comment]
Travis on github included. Can you try CMD+U. I tried shared XCODE scheme but I can't verify if it works.

**Comment by brunophilipe** [comment]
The problem was that the Tests scheme was not associated with the App. I fixed it by going to the "General" tab in the Tests scheme and selecting the main scheme as host app.

**Comment by xhruso00** [comment]
I tried to do logic tests which should not execute the app.
The switch you pulled runs the app with test. Travis on github does not require app to be executed
 "script: xctool test -project Cakebrew.xcodeproj -scheme CakebrewTests test". 
Will play with it later.

**Comment by brunophilipe** [comment]
Now the travis build is failing.

`Unable to read build settings for target 'CakebrewTests'.  It's likely that the scheme references a non-existent target.`

I have tried both schemes but it doesn't work.
```
xctool test -project Cakebrew.xcodeproj -scheme Cakebrew test
xctool test -project Cakebrew.xcodeproj -scheme CakebrewTests test
```

**Comment by xhruso00** [comment]
probably gitignore caused it. Will look at it

**Comment by xhruso00** [comment]
This commit deleted the scheme
https://github.com/brunophilipe/Cakebrew/commit/9965013bee89c34a3b1021e6efa6016cfc6811b0

**Pull request merged**
